version: "3"

services:
   backend:
      build: ./php
   frontend:
      build: ./public_html
      depends_on:
      - backend
      volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/usr/share/nginx/html
      ports:
      - 80:80
      - 443:443
